CREATE TABLE IF NOT EXISTS livros (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    genero VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);